### ISSUE TITLE
Sound notification

### ISSUE THREAD

**Issue by Lugicc** [anomalyce/twitter-idle-autorefresh#4]
Hey I love your plug-in it works perfect but would there be a possibility for you to add some sort of ping sound once a new tweet shows up after a refesh?

**Comment by anomalyce** [comment]
Hey @Lugicc!

Thank you for using my add-on and I'm glad it's working well for you! As far as playing a pinging sound goes, it is definitely something I could look into creating an optional setting for.

I've got a lot going on right now however and can't give you an estimated time for when I'll be able to get to it, but will do my best to look into it at the earliest convenience! :-)

**Comment by Lugicc** [comment]
Thanks for the quick reply! Great to hear you could make it work but no problem if not because it's already very usefull :D

**Comment by anomalyce** [comment]
I'll try to make it work at least, don't have much experience with playing audio through an add-on, haha. :-) But again, may take a little bit before I get the time to get started on it.

I'll ping you here when the feature is in place (or if it gets the better out of me).

**Comment by anomalyce** [comment]
I'm going to close this issue as I never got around to it and it's been several years. My apologies. If this is still something you really want, feel free to open up another issue and I'll revisit it.
