### ISSUE TITLE
Firefox not storing app settings

### ISSUE THREAD

**Issue by alejomedia** [anomalyce/twitter-idle-autorefresh#5]
Hi there,

Not sure if this page is still being checked but thought I'd give it a shot. This extension is actually working well despite the rebrand to X as of August 2023, but it doesn't appear to be saving any of the settings that I adjust in the add-ons menu. Anything I change just reverts to default on page refresh. Maybe the storage permission isn't working?

Firefox version: 115.0.2

Thanks for any help.

**Comment by alejomedia** [comment]
Actually, scratch that - I reinstalled the add-on a couple of times, and the save button now appears in the extension settings. No issue. Thanks for this! Good substitute for Tweetdeck.

**Comment by anomalyce** [comment]
Glad you managed to sort it! Let me know otherwise and I'll try to get some time in the near future to look into it.
